name: Build and deploy ASP.Net Core app to Azure Web App - recipe-search-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore ./src/RecipeSearch.Api/RecipeSearch.Api.csproj

      - name: Build
        run: dotnet build ./src/RecipeSearch.Api/RecipeSearch.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/RecipeSearch.Api/RecipeSearch.Api.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4B7A1EC111847CDAEA33BB7CB0FA217 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38E7599B3E5A45F6A1B7A2C2D91E87BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3AD4AAB92B2648F2AC646797D8A0B0BD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'recipe-search-api'
          slot-name: 'Production'
          package: ./publish